### ISSUE TITLE
Logic/state diagram for clicintip signals required

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-fast-interrupt#48] opened 2020-03-31 07:30 UTC
Section 3.4 (CLIC Interrupt Pending) attempts to describe the logic for `clicintip` signals, but I think this needs further clarification, either by a state diagram or a schematic. In particular, it says:

> `clicintip[i] `is a read-write register. Software-based (direct) writes to these pending bits have priority over hardware-based writes (triggers).

What does this mean if the input is configured as level-sensitive?

What state is latched and what is combinatorial? For example, what is the effect of reconfiguring a signal to be positive level-triggered instead of negative level-triggered while it is pending?

I think this section needs to fully describe the value of `clicintp` for every possible transition of the external input signal, corresponding `clicintie` and `clicintarttr` registers, and describe the effect of a software write to `clicintp` in every state.

**Comment by anthony-coulter** [comment] 2020-05-22 21:13
=== The CLIC triggering mechanism ===

The CLIC triggering mechanism for interrupt #i has the following components:

* The input signal from the interrupt source.
* Three configuration bits `trigger`, `polarity`, and `enable`
* An invisible storage bit `latch`
* The memory-accessible bit `pending`
* An input signal `autoclear` from the hart

The triggering mechanism thus latches four bits of state: `trigger`, `polarity`, `enable`, and `latch`.

=== Memory map of these bits ===

Four bits in the triggering mechanism are accessible via memory accesses:

* `trigger` is currently the second-least-significant bit of `clicintattr[i]`.
* `polarity` is currently the third-least-significant bit of `clicintattr[i]`.
* `enable` will probably be the least-significant bit of `clicintie[i]`.
* `pending` will probably be the least-significant bit of `clicintip[i]`.
* `latch` is not directly accessible in the memory map.

The value of the trigger bit is expressed with a symbolic constant: `LEVEL = 0` and `EDGE = 1`.

=== State of the bits on a reset ===

The state of the trigger, polarity, enable, and latch bits on a reset is unspecified. (The privileged spec already mandates that `mstatus.mie = 0` on reset, and that is enough to block all interrupts before they are configured by software.)

=== Reading these bits ===

Loads from the memory addresses corresponding to `trigger`, `polarity`, and `enable` read the saved bits as expected.

Loads from the memory address corresponding to `pending` returns the value:

        `pending := latch | (trigger == LEVEL & (source_signal ^ polarity)`

where `source_signal` is the signal from the interrupt handler.

When the CLIC determines whether an interrupt is pending for the purposes of taking an interrupt, it reads the `pending` bit the same way a memory access would.

=== Writing these bits ===

Stores to the memory addresses corresponding to `trigger`, `polarity`, and `enable` modify the stored values as expected.

A store to the `pending` bit changes the state of the `latch` bit.

Note that some of these bits may be hardwired, in which case storing to them has no effect.

=== Hardwiring considerations ===

The implementation MAY hardwire `trigger` to either `LEVEL` or `EDGE`.

The implementation MAY hardwire `polarity` to zero. It SHOULD NOT hardwire the `polarity` to one. (Rationale: Software can determine whether the polarity bit is reconfigurable by writing a 1 to it and seeing what happens. If the polarity bit is not configurable, there's no need for hardware to tell us whether the underlying physical signal is active-high or active-low, so we mandate that the hardwired value be zero.)

The implementation MAY hardwire `latch` to zero, but only if it also hardwires `trigger = LEVEL`. (Note that doing so makes it impossible for software to manually write to the pending bit.)

The implementation MUST NOT hardwire `enable` to zero. It MAY hardwire `enable` to one. (Hardwiring the enable bit to 1 creates a non-maskable interrupt. If we want to forbid that, then we should disallow hardwiring the enable bit to any value.)  

=== The autoclear signal ===

The `autoclear` signal is delivered to the interrupt triggering mechanism for interrupt #i under either of the following circumstances:

* `clicint[i].shv = 0` and interrupt #i is delivered to the hart.
* `clicint[i].shv = 1`, the hart writes to the `Xnxti` CSR, and the trap address returned corresponds to interrupt #i.

For ordering purposes: the hart writing to the `Xnxti` CSR is a regular instruction execution, and the hart accepting an interrupt must take place between some pair of consecutive instructions because interrupts are precise. Thus a hart cannot set the `pending` bit (with a store to `clicintip[i]`) concurrently with the delivery of the `autoclear` signal---one must logically precede the other.

=== Asynchronous changes to the latch bit ===

The `latch` bit can change under the following circumstances:

1. A store to the `pending` bit in the `clicintip[i]` byte will overwrite `latch` as expected.
2. The `latch` bit is set to 1 if `source_signal` changes from `polarity` to `!polarity` while `trigger == EDGE`. Note that `latch` is NOT set if software writes to `polarity` but `source_signal` does not experience an edge.
3. The `latch` bit is set to 0 when the `autoclear` signal arrives from the hart.

The `latch` bit will not change under any other circumstances.

=== Ordering considerations ===
The memory atomicity rule: If a hart updates multiple bits in the interrupt triggering mechanism with a single store to memory, the CLIC must not deliver the interrupt to the CPU if `pending = 0` both before and after the write completes. [Concrete example: A hart uses a store halfword instruction to simultaneously clear the pending bit while setting the enable bit. A bad implementation might update the enable bit before updating the latch, causing the pending bit to spuriously read high for less than one cycle. The CLIC must not treat this as a real interrupt request.]

Otherwise: the standard RISC-V memory ordering rules (either RVWMO or zTSO depending on the platform) govern the circumstances under which memory accesses to the CLIC may be reordered. In particular, if the hart stores zero to `clicintie[i]` and then stores one to `clicintip[i]` without putting a fence between them, an RVWMO implementation MAY reorder these stores and trigger a spurious interrupt. Also, if a hart changes the polarity and trigger bits with a store to `clicintattr[i]` and then loads `clicintip[i]`, the implementation MAY reorder the load before the store and deliver an old value of the `pending` bit that does not reflect the new configuration.  As usual, platforms are encouraged to make stronger guarantees, and portable software can avoid these issues with fence instructions.

=== Updates to the latch while the system is being reconfigured ===

Recall that `latch` is set to 1 if `source_signal` changes from `polarity` to `!polarity` while `trigger == EDGE`. This section describes situations under which the `latch` bit might not get updated.

Behavior is governed by the memory atomicity principle for edge detection:

If a single memory write updates more than one of the `trigger`, `polarity`, `enable`, and `pending` bits, then those updates must be applied atomically with respect to incoming edges. That is, the edge must be detected and `latch` updated either before any of these bits are written, or after all of them are written.

In that vein, an input pulse (a rising edge followed immediately by a falling edge, or vice versa) must be ordered in one of three ways:

1. reconfiguration, rising edge, falling edge
2. rising edge, reconfiguration, falling edge
3. rising edge, falling edge, reconfiguration

I see one particularly interesting outcome of this model. Suppose an interrupt is configured with `trigger = EDGE` and `polarity = 0` and the input line is idling at zero. Then software reconfigures `polarity = 1` at the same time the signal undergoes a positive pulse (rising edge followed by falling edge). In this case `latch` MUST be updated, and it is illegal for the trigger mechanism to "miss" the pulse. But in the same situation, if the `polarity` started at 1 and was reconfigured to zero when a positive pulse comes in, it would be an allowable outcome for the latch to miss both edges because the reconfiguration could take place between them.

=== Example uses ===

1. A pure software interrupt:

Hardwire the input signal to one, `polarity` to zero, and `trigger` to whichever of `LEVEL`/`EDGE` encodes as zero. This has the effect of making the `pending` bit an alias of latch bit. Software interrupts are thus triggered only when a hart writes to the `pending` bit.

2. A cheap level-triggered interrupt:

Hardwire `trigger = LEVEL` and `latch = 0`. Reading the `pending` bit will return `xor(signal, polarity)`. Writing to `pending` has no effect.

3. Configuring an interrupt with a single store-word

A single store-word instruction can set `pending = 0`, `enable = 1`, and `trigger` and `polarity` to anything. This will clear the latch, enable the interrupt, and reconfigure trigger and polarity in such a way that no spurious interrupt is generated (because a write to the polarity bit MUST NOT be interpreted by hardware as an edge in the input line).

Note that in general, software is responsible for clearing the latch bit when it changes the trigger type.

=== Regarding the latch bit for level-triggered interrupts ===

This proposal allows software to generate a fake level-triggered interrupt by writing to the pending bit, which sets the latch and causes subsequent reads of the pending bit to return true. This looks crazy but my rationale is as follows:

1. Implementations are permitted to hardwire the latch bit to zero if they have also hardwired the trigger bit to LEVEL, so you can leave out most of the circuitry if you know you'll never use it.

2. Incoming edges do not set the latch bit to 1 unless the `trigger == EDGE`, so only way to set the latch for a level-triggered interrupt is by a software write to the pending bit, which is a use case called out in the current CLIC draft.

3. If someone tries to fake a level-triggered interrupt by storing a 1 to the pending bit, then the latch will immediately be cleared (by the autoclear signal) as soon as the interrupt is taken. Software is not responsible for clearing the latch manually, and if it wasn't expecting to have to handle fake software-triggered interrupts it will notice that the pending bit is no longer set and assume that the input signal has dropped back to its original level.

4. As stated earlier, software can easily clear the latch whenever it reconfigures the trigger type in a single store-word instruction, so the burden of managing the latch during reconfigurations is minimal. In particular, clearing the latch on a reconfiguration in software requires less complexity than doing it in hardware.

**Comment by JamesKenneyImperas** [comment] 2020-05-26 11:12
This level of detail is excellent and exactly what is needed in the specification.

**Comment by anthony-coulter** [comment] 2020-05-26 13:31
There seems to be some resistance on the mailing list to the idea of keeping the latch around for level-triggered interrupts. To summarize my thinking about it (repeating a few points from the end of my proposal):
* The latch is optional for level-triggered-only interrupts; the proposal doesn't mandate that people add a latch to an implementation that doesn't need one.
* Edge-triggered interrupts and software interrupts both require a latch, so for configurable interrupts we need to specify the latch's behavior in level-triggered mode.
* This proposal gives a uniform description of how all interrupt types (level-triggered, edge-triggered, and software-written) can be expected to behave in the presence of a latch, while still allowing pure level-triggered interrupts to operate without a latch.

A counterproposal on the mailing list is to leave the latch behavior unspecified on reconfiguration. To fill in some details:
* The latch would be ignored in level-triggered mode; that is,
    pending := (trigger == EDGE & latch) | (trigger == LEVEL & (source_signal ^ polarity)
* The state of the latch after interrupts are reconfigured to `EDGE` is unspecified. (And the state of the latch while `trigger == LEVEL` is irrelevant.)
* Changing `polarity` while `trigger == EDGE` may or may not trigger a spurious interrupt. (This was not stated in the counterproposal, but I think it fits the spirit thereof.)
* To change the interrupt configuration deterministically, software should disable interrupts, then update `trigger` and/or `polarity`, and then then reenable/reinitialize interrupts.

I would push back on the third point: software should be able to reconfigure interrupts in a single instruction, so I would contend that a single store-word instruction to set `pending`/`enable`/`trigger`/`polarity` all at once ought to initialize the interrupt into a deterministic state.

**Comment by silabs-PaulZ** [comment] 2020-07-10 19:21
For the purpose of this discussion, I will use the term ‘sticky’ in lieu of ‘latch’.

In order to properly provide an edge-based interrupt, the CLIC will probably need to add three additional flops (or latches) per interrupt: 1) edge mode via clicintaatr.trig[0], 2)edge detection, 3)sticky capture. This is a little expensive for our case, a low power, low gate count embedded processor. Here’s an example implementation for discussion (not guaranteed, does not include all features such as SW setting/clearing pending )
![image](https://user-images.githubusercontent.com/59703134/87189164-ca78b980-c2b5-11ea-974c-b1d77389c0f1.png)
With the current specification, the CLIC will be able to capture the three types of interrupts: level, edge, and pulse (the latter using the edge-based setting).

From an embedded point of view, we require pulse and level interrupts, but not the edge-based.  Enabling pulse and level will result in the 'expensive' edge-based mechanism.



In order to reduce the overall number of flops and provide a simple interrupt protocol, I propose to always capture the input interrupt into a sticky pending bit.
The proposed behavior is as follows: 
  - The interrupt will be captured into a sticky pending status when associated ISR is not active. 
  - Interrupt pending is automatically cleared by HW while the associated ISR is active.

Here’s an example implementation for discussion only.
![image](https://user-images.githubusercontent.com/59703134/87189487-58ed3b00-c2b6-11ea-8269-59655e4c0de8.png)

Pros:
  - Removes the need for clicintattr.trig[0] edge/level mode flop
  - Removes the edge detection circuitry
  - Only one sticky capture needed to support pulse and level
  - The software does not need to clear pending (same as CLIC)
  - The software can always set pending directly (not shown above)
Cons:
  - Removes true edge-based interrupt detection

If this proposal is not accepted, we will need to define the behavior of the edge-based interrupt in more detail:

What is the expected behavior of the sticky/pending bit when an edge-based interrupt level is maintained high throughout the ISR?
![image](https://user-images.githubusercontent.com/59703134/87189590-889c4300-c2b6-11ea-8b36-026716ccd8df.png)

What is the expected behavior of the sticky/pending bit when an edge-based interrupt occurs during the ISR (but after it was originally auto cleared). Is it expected to return to the ISR after it exits?
![image](https://user-images.githubusercontent.com/59703134/87189631-96ea5f00-c2b6-11ea-938b-579dbc7378a8.png)

Should we instead clear the pending status at the end of the ISR?


Can people provide examples where they need a true edge-based vs. pulse?

**Comment by kasanovic** [comment] 2021-08-03 16:45
These issues were addressed in later edits to the spec.  However, Section 4.4 should be edited to be clearer about when hardware clears the IP bits as seen by software. Also, should refer to other sections that describe how edge-triggered interrupts are cleared.

Also for software clearing of the IP bit,  only writes to the xnxti can clear the bit, not read-only accesses.

Waveforms are too implementation-specific to be used in the spec.  Some cores will be asynchronous....

**Closed** 2021-11-09 17:31 UTC
